baseURL = 'https://singh2005.github.io/scamurai-website/'
languageCode = 'en-us'
title = 'Scamurai'
theme = 'PaperMod'

[params]
  mainSections = ['posts']
  defaultTheme = "auto"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 10
