name: Fetch Mastodon Toots

on:
  schedule:
    - cron: "0 * * * *" # every hour
  workflow_dispatch:

jobs:
  fetch-toots:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - name: Configure Git
      run: |
        git config user.name "Shailendra Singh"
        git config user.email "singh2005@gmail.com"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install Mastodon.py

    - name: Run fetch_toots.py
      env:
        MASTODON_BASE_URL: https://mastodon.social
        MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
      run: python scripts/fetch_toots.py

    - name: Commit & push changes
      run: |
        git add content/posts/*.md
        git commit -m "Add new scam alert posts from Mastodon" || echo "No changes to commit"
        git push
